branches:
  only:
    - master

clone_folder: C:\projects\pyrxp

environment:
  global:
    REPO_DIR: C:\projects\pyrxp
    TWINE_USERNAME: MrRLBitBucket
    TWINE_PASSWORD:
      secure: 7XgI2S6O+eY0YtqvwbIk0F5Ism+kJq7vn1S1oSKlx08=
    CITOOLS_USER: rl-wheelbuilder
    CITOOLS_PASSWORD:
      secure: xbq9uLuFeus1N1x8xSF9f5kAYXY4lkvU4UveYwgcMkM=
    FIRST: 27
    LAST: 38-x64
    RLCACHE: windows/pyrxp

  matrix:
    - PYVER: 27
      ARCH: X86

    - PYVER: 27-x64
      ARCH: AMD64

    - PYVER: 35
      ARCH: X86

    - PYVER: 35-x64
      ARCH: AMD64

    - PYVER: 36
      ARCH: X86

    - PYVER: 36-x64
      ARCH: AMD64

    - PYVER: 37
      ARCH: X86

    - PYVER: 37-x64
      ARCH: AMD64

    - PYVER: 38
      ARCH: X86

    - PYVER: 38-x64
      ARCH: AMD64

matrix:
  fast_finish: true

install:
  - cmd: echo "=============================== Python%PYVER% install FIRST='%FIRST%' LAST='%LAST%'"
  - "SET PATH=C:\\Python%PYVER%;c:\\Python%PYVER%\\scripts;%PATH%"
  - ps: |
        $py_exe = "C:\Python${env:PYVER}\Python.exe"
        if ( -Not ([System.IO.File]::Exists($py_exe)) ) {
            if ( -Not ([System.IO.File]::Exists("C:\projects\install_python.ps1")) ) {
                Write-Host "Fetching install_python.ps1" -ForegroundColor Yellow
                curl -o C:\projects\install_python.ps1 https://www.reportlab.com/ftp/install_python.ps1
                if ( -Not ([System.IO.File]::Exists("C:\projects\install_python.ps1")) ) {
                    Write-Host "C:\projects\install_python.ps1 was not fetched" -ForegroundColor Red
                    exit 1
                }
            }
            C:\projects\install_python.ps1
        }
  - cmd: echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - cmd: c:\Python37-x64\python.exe -mvirtualenv c:\projects\reportlab\myenv
  - cmd: c:\projects\pyrxp\myenv\scripts\pip.exe install https://bitbucket.org/MrRLBitBucket/rl_ci_tools/get/tip.tar.gz
  - cmd: if not exist C:\Python%PYVER%\python.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\python.exe not found" && exit 1 )
  - cmd: if not exist C:\Python%PYVER%\scripts\pip.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\scripts\pip.exe not found" && exit 1 )

build_script:
  - if "%PYVER%" == "%FIRST%" c:\projects\pyrxp\myenv\scripts\python.exe -mrl_ci_tools clear-cache %RLCACHE%
  - cmd: if not exist C:\Python%PYVER%\python.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\python.exe not found" && exit 1 )
  - cmd: if not exist C:\Python%PYVER%\scripts\pip.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\scripts\pip.exe not found" && exit 1 )
  - cmd: c:\Python%PYVER%\python.exe -mpip install -U pip setuptools wheel
  - cmd: c:\Python%PYVER%\scripts\pip.exe --version
  - cmd: c:\Python%PYVER%\scripts\pip.exe install wheel
  - cmd: c:\Python%PYVER%\python.exe -W ignore setup.py bdist_wheel

on_success:
  - echo "=============================== Python%PYVER% on_success"
  - if "%PYVER%" == "%LAST%" c:\projects\pyrxp\myenv\scripts\python.exe -mrl_ci_tools env
  - c:\projects\pyrxp\myenv\scripts\python.exe -mrl_ci_tools upload-caches --subdir=%RLCACHE% --verbosity=1 dist/*.whl
  - if "%PYVER%" == "%LAST%" c:\projects\pyrxp\myenv\scripts\python.exe -mrl_ci_tools email --subject="+++++ APPVEYOR %APPVEYOR_PROJECT_NAME% build succeeded" --faddr=rl-wheelbuilder --body="see https://www.reportlab.com/pypi/cache-info/%RLCACHE%/*/"

on_failure:
  - c:\projects\pyrxp\myenv\scripts\python.exe -mrl_ci_tools email --subject="!!!!! APPVEYOR %APPVEYOR_PROJECT_NAME% build failed" --faddr=rl-wheelbuilder --body="see https://ci.appveyor.com/project/MrRLBitBucket/%PROJECT_NAME%/history"

#test_script:
# - python setup.py test -q

#artifacts:
#  - path: 'mydist\*.whl'
#    name: wheel

#deploy_script:
  #- ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist/* }
  #- c:\projects\pyrxp\myenv\scripts\python -mrl_ci_tools upload-packages --verbosity=1 mydist\*.whl

deploy: off
