environment:
  global:
    TWINE_USERNAME: MrRLBitBucket
    TWINE_PASSWORD:
      secure: 7XgI2S6O+eY0YtqvwbIk0F5Ism+kJq7vn1S1oSKlx08=
    CITOOLS_USER: rl-wheelbuilder
    CITOOLS_PASSWORD:
      secure: xbq9uLuFeus1N1x8xSF9f5kAYXY4lkvU4UveYwgcMkM=
    FIRST: 27
    LAST: 36-x64
    #LAST: 27-x64
    RLCACHE: windows/pyrxp

  matrix:
    - python: 27
    - python: 27-x64
    - python: 33
    - python: 33-x64
    - python: 34
    - python: 34-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64

matrix:
  fast_finish: true

install:
  - cmd: echo "=============================== Python%PYTHON% install FIRST='%FIRST%' LAST='%LAST%'"
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - cmd: echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - cmd: c:\Python27-x64\python.exe -mvirtualenv myenv
  - cmd: myenv\scripts\pip.exe install https://bitbucket.org/MrRLBitBucket/rl_ci_tools/get/tip.tar.gz
# - pip install -e .



build_script:
  - if "%PYTHON%" == "%FIRST%" myenv\scripts\python.exe -mrl_ci_tools clear-cache %RLCACHE%
  - cmd: pip install wheel
  - cmd: python -W ignore setup.py -q bdist_wheel

on_success:
  - echo "=============================== Python%PYTHON% on_success"
  - if "%PYTHON%" == "%LAST%" myenv\scripts\python.exe -mrl_ci_tools env
  - myenv\scripts\python.exe -mrl_ci_tools upload-caches --subdir=%RLCACHE% --verbosity=1 dist/*.whl
  - if "%PYTHON%" == "%LAST%" myenv\scripts\python.exe -mrl_ci_tools email --subject="+++++ APPVEYOR %APPVEYOR_PROJECT_NAME% build succeeded" --faddr=rl-wheelbuilder --body="see https://www.reportlab.com/pypi/cache-info/%RLCACHE%/*/"

on_failure:
  - myenv\scripts\python.exe -mrl_ci_tools email --subject="!!!!! APPVEYOR %APPVEYOR_PROJECT_NAME% build failed" --faddr=rl-wheelbuilder --body="see https://ci.appveyor.com/project/MrRLBitBucket/%PROJECT_NAME%/history"

#test_script:
# - python setup.py test -q

#artifacts:
#  - path: 'mydist\*.whl'
#    name: wheel

#deploy_script:
  #- ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist/* }
  #- myenv\scripts\python -mrl_ci_tools upload-packages --verbosity=1 mydist\*.whl

deploy: off
